site_name: SSIX Protocol

site_description: Sustainable Supply Information Exchange (SSIX) Protocol Documentation

theme:
  name: material


nav:
  - Home: 'index.md'
  - About: 'whatisssix.md'
  - Mission: 'ssixmission.md'
  - Specification: 'specification.md'
