site_name: SSIX Protocol

site_description: Sustainable Supply Information Exchange (SSIX) Protocol Documentation

theme:
  name: material


nav:
  - Home: 'index.md'
  - About: 'whatisssix.md'
  - Mission: 'ssixmission.md'
  - Specification: 'specification.md'
    - Types: 'types.md'
    - Common Objects: 'specification-common.md'
    - Entities: 'entity.md'
    - Documents: 'document.md'
    - Trades: 'trade.md'
